spring.application.name=library-system
logging.level.root=INFO

spring.datasource.url=jdbc:mysql://localhost:3306/experiment_01_library?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.example.experiment2.entity
mybatis.configuration.map-underscore-to-camel-case=true
